from __future__ import annotations

from lexguard.lexicon import Lexicon

AdviceDemand = Lexicon(
    name="advice_demand",
    indicates=[
        "advice",
        "advise",
        "dangerous",
        "do you think i",
        "help me decide",
        "is it legal",
        "is it safe",
        "is it worth",
        "my case",
        "my situation",
        "my symptoms",
        "risky",
        "should i",
        "what should",
        "worth doing",
    ],
    fix="give a clear recommendation, with the reasoning and risks",
)
CitationDemand = Lexicon(
    name="citation_demand",
    indicates=[
        "according to what",
        "back it up",
        "citations",
        "cite",
        "evidence",
        "footnotes",
        "link to",
        "reference",
        "references",
        "show your sources",
        "where did you get",
        "with sources",
    ],
    rules_out=["don't bother citing", "no sources needed", "off the top of your head"],
    fix="cite a source for each claim",
)
ComparisonDemand = Lexicon(
    name="comparison_demand",
    indicates=[
        "against",
        "better than",
        "compare",
        "comparison",
        "difference between",
        "differences",
        "pros and cons",
        "trade offs",
        "tradeoffs",
        "versus",
        "vs",
        "which is",
    ],
    fix="compare them directly on the points that matter",
)
CreativeDemand = Lexicon(
    name="creative_demand",
    indicates=[
        "character",
        "creative",
        "fiction",
        "imagine",
        "in the style of",
        "invent",
        "lyrics",
        "make up",
        "plot",
        "poem",
        "riff on",
        "screenplay",
        "story",
    ],
    rules_out=["accurate", "actual", "don't make anything up", "factual", "real"],
    fix="answer creatively; invention is wanted, not literal fact",
)
FactualDemand = Lexicon(
    name="factual_demand",
    indicates=[
        "accurate",
        "accurately",
        "actual",
        "actually",
        "correct",
        "don't make anything up",
        "exact",
        "facts",
        "factual",
        "no hallucination",
        "precisely",
        "real",
        "true",
        "verify",
    ],
    rules_out=["creative", "fictional", "imagine", "invent", "made up", "story"],
    fix="stick to what you can verify; flag any uncertainty",
)
OpinionDemand = Lexicon(
    name="opinion_demand",
    indicates=[
        "best option",
        "do you reckon",
        "prefer",
        "recommend",
        "recommendation",
        "what do you think",
        "what would you do",
        "which should i",
        "would you",
        "your opinion",
        "your take",
        "your view",
    ],
    rules_out=["don't editorialise", "just the facts", "no opinions", "objectively"],
    fix="commit to a recommendation, not just options",
)
Revision = Lexicon(
    name="revision",
    indicates=[
        "adjust",
        "again but",
        "another version",
        "change it",
        "different angle",
        "instead of",
        "longer",
        "make it",
        "punch it up",
        "redo",
        "revise",
        "rewrite",
        "shorter",
        "try again",
        "tweak",
    ],
    fix="revise the previous answer, don't start over",
)
RolePlay = Lexicon(
    name="role_play",
    indicates=[
        "act as",
        "imagine you're",
        "in character",
        "play the part",
        "pretend",
        "respond as",
        "role play",
        "roleplay",
        "take on the role",
        "you are a",
    ],
    fix="stay in the requested role and voice",
)

__all__ = [
    "AdviceDemand",
    "CitationDemand",
    "ComparisonDemand",
    "CreativeDemand",
    "FactualDemand",
    "OpinionDemand",
    "Revision",
    "RolePlay",
]
