from __future__ import annotations

from lexguard.lexicon import Lexicon, Source

CitationMarker = Lexicon(
    name="citation_marker",
    indicates=[
        "according to",
        "cited",
        "doi",
        "https",
        "per the",
        "published in",
        "reference",
        "references",
        "reported by",
        "see",
        "source",
        "sources",
    ],
    fix="attach a source to each factual claim the user could act on",
)
Disclaimer = Lexicon(
    name="disclaimer",
    indicates=[
        "consult a professional",
        "consult a qualified",
        "do your own research",
        "for informational purposes",
        "i'm not a doctor",
        "i'm not a lawyer",
        "not a substitute",
        "not financial advice",
        "not legal advice",
        "not medical advice",
        "seek professional",
        "speak to a",
        "this is general",
        "your mileage may vary",
    ],
    fix="only warn when the user is about to act on the answer, and say it once",
)
Hedging = Lexicon(
    name="hedging",
    indicates=[
        "apparently",
        "appears to",
        "arguably",
        "broadly speaking",
        "conceivably",
        "could potentially",
        "for the most part",
        "generally",
        "in general",
        "in many ways",
        "in some cases",
        "it depends",
        "likely",
        "may",
        "might",
        "more or less",
        "often",
        "perhaps",
        "plausibly",
        "possibly",
        "presumably",
        "probably",
        "relatively",
        "seems",
        "somewhat",
        "tends to",
        "to some extent",
        "typically",
        "usually",
    ],
    rules_out=[
        "certainly",
        "definitely",
        "guaranteed",
        "i could be wrong",
        "i don't know",
        "i'm not sure",
        "no doubt",
        "uncertain",
        "undoubtedly",
    ],
    fix=(
        "commit to a claim or say plainly that you do not know; stacked qualifiers are not "
        "calibration"
    ),
    evidence=(
        Source(cite="Lakoff 1973", url="https://doi.org/10.1007/BF00262952"),
        Source(cite="Hyland 2005 (hedges)", url=""),
        Source(cite="CoNLL-2010 uncertainty cues", url="https://aclanthology.org/W10-3001/"),
    ),
)
Overclaim = Lexicon(
    name="overclaim",
    indicates=[
        "100%",
        "always",
        "beyond doubt",
        "bulletproof",
        "cannot fail",
        "certainly",
        "certainly will",
        "clearly",
        "completely safe",
        "definitely",
        "definitely will",
        "foolproof",
        "guaranteed",
        "guarantees",
        "indisputably",
        "never fails",
        "no doubt",
        "no risk",
        "obviously",
        "perfect solution",
        "proven to",
        "the best",
        "the only",
        "undeniably",
        "undoubtedly",
        "unequivocally",
        "unquestionably",
        "without a doubt",
        "without question",
    ],
    rules_out=["depends", "in some cases", "may", "might", "typically"],
    fix=(
        "state the condition under which the claim holds, or downgrade it to what the evidence "
        "supports"
    ),
    evidence=(Source(cite="Hyland 2005 (boosters)", url=""),),
)
UncertaintyAdmission = Lexicon(
    name="uncertainty_admission",
    indicates=[
        "i am not sure",
        "i can't be certain",
        "i could be wrong",
        "i don't know",
        "i may be misremembering",
        "i'd need to check",
        "i'm not sure",
        "i'm uncertain",
        "without checking",
        "worth verifying",
    ],
    fix="say what you are unsure about and what would resolve it",
    evidence=(
        Source(cite="CoNLL-2010 uncertainty cues", url="https://aclanthology.org/W10-3001/"),
    ),
)
UnsourcedAuthority = Lexicon(
    name="unsourced_authority",
    indicates=[
        "common knowledge",
        "critics say",
        "data suggests",
        "evidence shows",
        "experts agree",
        "experts say",
        "it has been claimed",
        "it is believed",
        "it is said",
        "it is thought",
        "it is widely",
        "it's well established",
        "many argue",
        "many believe",
        "reportedly",
        "research indicates",
        "research shows",
        "science says",
        "some argue",
        "some say",
        "sources say",
        "studies have shown",
        "studies show",
        "widely known",
        "widely regarded",
    ],
    fix="name the source or drop the appeal; vague authority is worse than no authority",
    evidence=(
        Source(cite="Ganter & Strube 2009", url="https://aclanthology.org/P09-2044/"),
        Source(
            cite="Recasens et al. 2013 (weasel words)", url="https://aclanthology.org/P13-1162/"
        ),
    ),
)
UnverifiedClaim = Lexicon(
    name="unverified_claim",
    indicates=[
        "all good now",
        "bug is fixed",
        "bug is gone",
        "done and working",
        "everything works now",
        "fixed it",
        "good to go",
        "it works now",
        "no more errors",
        "now it works",
        "problem solved",
        "that did the trick",
        "that fixes it",
        "that's fixed",
        "the fix works",
        "this fixes it",
        "this resolves it",
        "this will work",
        "this works now",
        "works as expected",
        "works perfectly",
        "you're all set",
    ],
    rules_out=[
        "hopefully",
        "i confirmed",
        "i tested",
        "i think",
        "in theory",
        "might",
        "not sure",
        "output shows",
        "probably",
        "ran the tests",
        "should",
        "tests pass",
        "tests passed",
        "the logs show",
        "verified",
    ],
    fix="run it and show the result before claiming it works, or say you have not verified it",
    evidence=(
        Source(
            cite="Huang et al. 2024 (intrinsic self-correction limits)",
            url="https://arxiv.org/abs/2310.01798",
        ),
        Source(cite="Hyland 2005 (boosters)", url=""),
    ),
)

__all__ = [
    "CitationMarker",
    "Disclaimer",
    "Hedging",
    "Overclaim",
    "UncertaintyAdmission",
    "UnsourcedAuthority",
    "UnverifiedClaim",
]
