from __future__ import annotations

from lexguard.lexicon import Lexicon

Attachment = Lexicon(
    name="attachment",
    indicates=[
        "attached",
        "attachment",
        "forwarded",
        "in the email",
        "link",
        "pdf",
        "photo",
        "screenshot",
        "see the doc",
        "spreadsheet",
        "the thread",
        "url",
    ],
    fix="keep the referenced file or link with it",
)
Confirmation = Lexicon(
    name="confirmation",
    indicates=[
        "agreed",
        "all set",
        "book it",
        "confirmed",
        "definitely",
        "do it",
        "for sure",
        "go ahead",
        "locked in",
        "sorted then",
        "that's the one",
        "yes please",
    ],
    rules_out=["maybe", "might", "not sure", "provisionally", "tentatively", "we'll see"],
    fix="go ahead; don't ask again",
    fail_when_neutral=True,
)
Correction = Lexicon(
    name="correction",
    indicates=[
        "change that",
        "correction",
        "i meant",
        "make that",
        "no wait",
        "on second thoughts",
        "other way round",
        "scratch that",
    ],
    rules_out=[
        "as i said",
        "keep it as is",
        "leave it as is",
        "like i said",
        "no change",
        "same as before",
        "stick with",
    ],
    fix="use the corrected version, not the earlier one",
)
Exception = Lexicon(
    name="exception",
    indicates=[
        "apart from",
        "besides",
        "but not",
        "except",
        "excluding",
        "not on",
        "other than",
        "save for",
        "skip",
        "unless",
    ],
    fix="apply the exclusion; leave the exempted case out",
)
Hypothetical = Lexicon(
    name="hypothetical",
    indicates=[
        "considering",
        "could",
        "depending",
        "if",
        "in case",
        "maybe",
        "might",
        "not sure",
        "perhaps",
        "possibly",
        "potentially",
        "provisionally",
        "suppose",
        "tentatively",
        "thinking about",
        "undecided",
        "we'll see",
        "what if",
        "wondering",
    ],
    rules_out=["book it", "confirmed", "definitely", "do it", "for sure", "go ahead"],
    fix="hold off until it's confirmed",
)
Negation = Lexicon(
    name="negation",
    indicates=[
        "avoid",
        "can't",
        "cannot",
        "didn't",
        "do not",
        "doesn't",
        "don't",
        "mustn't",
        "neither",
        "never",
        "no",
        "no need",
        "none",
        "nor",
        "not",
        "not needed",
        "rather not",
        "shouldn't",
        "without",
        "won't",
    ],
    fix="honour what is ruled out; don't include it",
)
Placeholder = Lexicon(
    name="placeholder",
    indicates=[
        "dummy",
        "example",
        "fixme",
        "insert",
        "ipsum",
        "lorem",
        "n/a",
        "none",
        "null",
        "placeholder",
        "tba",
        "tbc",
        "tbd",
        "temp",
        "temporary",
        "unknown",
        "unnamed",
        "unspecified",
        "untitled",
        "xxx",
        "your text here",
    ],
    fix="fill the value or ask for it; a template marker reaching the user is an unfinished output",
)
PriorReference = Lexicon(
    name="prior_reference",
    indicates=[
        "again",
        "as usual",
        "earlier",
        "from yesterday",
        "like before",
        "mentioned",
        "same as",
        "that one",
        "the one",
        "the other",
        "the usual",
        "we discussed",
        "you added",
    ],
    fix="resolve it against what came before",
)
Question = Lexicon(
    name="question",
    indicates=[
        "any",
        "anything",
        "are",
        "can",
        "could",
        "did",
        "do",
        "do i have",
        "does",
        "have i got",
        "how",
        "is",
        "list",
        "should",
        "show me",
        "tell me",
        "was",
        "were",
        "what",
        "what's on",
        "when",
        "where",
        "which",
        "who",
        "whom",
        "whose",
        "why",
        "will",
        "would",
    ],
    rules_out=["add", "create", "make a note", "remind me"],
    fix="answer the question; don't turn it into a task",
)
Vague = Lexicon(
    name="vague",
    indicates=[
        "a few",
        "anything",
        "bits",
        "kind of",
        "some",
        "something",
        "sort of",
        "stuff",
        "that thing",
        "the usual",
        "things",
        "whatever",
        "you know",
    ],
    fix="resolve the referent from context or ask one clarifying question",
)

__all__ = [
    "Attachment",
    "Confirmation",
    "Correction",
    "Exception",
    "Hypothetical",
    "Negation",
    "Placeholder",
    "PriorReference",
    "Question",
    "Vague",
]
