from __future__ import annotations

from ..lexicon import Lexicon

DueDate = Lexicon(
    name="due_date",
    indicates=[
        "after",
        "afternoon",
        "apr",
        "april",
        "aug",
        "august",
        "before",
        "by",
        "cob",
        "day after tomorrow",
        "deadline",
        "dec",
        "december",
        "due",
        "end of the day",
        "end of the week",
        "eod",
        "eow",
        "evening",
        "feb",
        "february",
        "first thing",
        "fortnight",
        "fri",
        "friday",
        "in the morning",
        "jan",
        "january",
        "jul",
        "july",
        "jun",
        "june",
        "mar",
        "march",
        "may",
        "midday",
        "midnight",
        "mon",
        "monday",
        "month",
        "morning",
        "next month",
        "next week",
        "night",
        "noon",
        "nov",
        "november",
        "oct",
        "october",
        "quarter",
        "sat",
        "saturday",
        "sep",
        "sept",
        "september",
        "sun",
        "sunday",
        "this evening",
        "thu",
        "thurs",
        "thursday",
        "till",
        "today",
        "tomorrow",
        "tonight",
        "tue",
        "tues",
        "tuesday",
        "until",
        "wed",
        "wednesday",
        "week",
        "weekday",
        "weekend",
        "year",
        "yesterday",
    ],
    rules_out=[
        "at some point",
        "eventually",
        "no deadline",
        "no hurry",
        "no particular time",
        "no rush",
        "open ended",
        "someday",
        "sometime",
        "when i get round to it",
        "whenever",
    ],
    fix="a due date is present: put it on the task and remind ahead of it",
)


ClockTime = Lexicon(
    name="clock_time",
    indicates=[
        "afternoon",
        "am",
        "breakfast",
        "dinner",
        "evening",
        "first thing",
        "half past",
        "lunchtime",
        "midday",
        "midnight",
        "morning",
        "noon",
        "o'clock",
        "pm",
        "quarter past",
        "quarter to",
        "teatime",
        "tonight",
    ],
    rules_out=[
        "all day",
        "any time",
        "no particular time",
        "some time",
        "whenever",
    ],
    fix="a time of day is present: set it on the task and remind at it",
)


Recurrence = Lexicon(
    name="recurrence",
    indicates=[
        "always on",
        "annually",
        "biweekly",
        "daily",
        "each",
        "every",
        "every other",
        "fortnightly",
        "monthly",
        "nightly",
        "on weekdays",
        "on weekends",
        "quarterly",
        "recurring",
        "regularly",
        "repeat",
        "repeating",
        "repeats",
        "routine",
        "weekly",
        "yearly",
    ],
    rules_out=[
        "every now and then",
        "every once in a while",
        "every so often",
        "just once",
        "once",
        "one off",
        "one time",
        "single",
        "this once",
    ],
    fix="a recurring task: make it repeat on that cadence, not a one-off",
)


Past = Lexicon(
    name="past",
    indicates=[
        "ago",
        "earlier",
        "forgot to",
        "last month",
        "last night",
        "last week",
        "missed",
        "overdue",
        "should have",
        "was supposed",
        "yesterday",
    ],
    fix="this refers to a missed task: log it as overdue, don't schedule it as new",
)


Duration = Lexicon(
    name="duration",
    indicates=[
        "all afternoon",
        "all day",
        "all morning",
        "brief",
        "for a bit",
        "for an hour",
        "half hour",
        "hour",
        "hours",
        "lasts",
        "long",
        "mins",
        "minutes",
        "quick",
        "takes",
    ],
    fix="a duration is given: record it so the task fits a matching free block",
)


# HighPriority and LowPriority are opposite poles of one axis: each rules out every one of the
# other's indicators (a full mirror), so any mix denies both and the two lists cannot drift.
# tests/test_exclusive_families.py enforces that. Note bare "priority" is deliberately not an
# indicator: it is a substring of "low priority", so as the opposite's blocker it would deny
# "low priority" itself — "high priority" / "top priority" carry the signal instead.
HighPriority = Lexicon(
    name="high_priority",
    indicates=[
        "asap",
        "blocking",
        "can't wait",
        "critical",
        "drop everything",
        "emergency",
        "first thing",
        "high priority",
        "immediately",
        "important",
        "needs doing now",
        "pressing",
        "right away",
        "right now",
        "straight away",
        "top priority",
        "urgent",
        "urgently",
    ],
    rules_out=[
        "at some point",
        "backlog",
        "eventually",
        "if i get a chance",
        "low priority",
        "maybe later",
        "nice to have",
        "no hurry",
        "no rush",
        "not urgent",
        "someday",
        "sometime",
        "when i get round to it",
        "when you can",
        "whenever",
    ],
    fix="marked urgent: surface it ahead of everything else, not the normal queue",
)


LowPriority = Lexicon(
    name="low_priority",
    indicates=[
        "at some point",
        "backlog",
        "eventually",
        "if i get a chance",
        "low priority",
        "maybe later",
        "nice to have",
        "no hurry",
        "no rush",
        "someday",
        "sometime",
        "when i get round to it",
        "whenever",
    ],
    rules_out=[
        "asap",
        "blocking",
        "can't wait",
        "critical",
        "deadline",
        "drop everything",
        "emergency",
        "first thing",
        "high priority",
        "immediately",
        "important",
        "needs doing now",
        "now",
        "pressing",
        "right away",
        "right now",
        "straight away",
        "today",
        "top priority",
        "urgent",
        "urgently",
    ],
    fix="marked low priority: send it to the backlog, don't rank it above real work",
)


Actionable = Lexicon(
    name="actionable",
    indicates=[
        "add",
        "apply",
        "arrange",
        "book",
        "book in",
        "bring",
        "buy",
        "call",
        "cancel",
        "chase",
        "check",
        "clean",
        "collect",
        "create",
        "don't forget",
        "draft",
        "drop",
        "email",
        "feed",
        "fetch",
        "file",
        "finish",
        "fix",
        "follow up",
        "get in touch",
        "hoover",
        "look into",
        "make",
        "message",
        "must",
        "need to",
        "order",
        "pack",
        "pay",
        "pick",
        "plan",
        "post",
        "prepare",
        "print",
        "register",
        "remember to",
        "remind",
        "renew",
        "repair",
        "return",
        "review",
        "ring",
        "schedule",
        "send",
        "sign",
        "sort",
        "sort out",
        "start",
        "submit",
        "take",
        "text",
        "tidy",
        "walk",
        "wash",
        "water",
        "write",
    ],
    rules_out=[
        "already done",
        "for information",
        "forget it",
        "fyi",
        "ignore that",
        "just saying",
        "just wondering",
        "never mind",
        "no action",
        "no need",
    ],
    fix="this is an instruction to act: create a task, don't just file a note",
)


Question = Lexicon(
    name="question",
    indicates=[
        "any",
        "anything",
        "are",
        "can",
        "could",
        "did",
        "do",
        "do i have",
        "does",
        "have i got",
        "how",
        "is",
        "list",
        "should",
        "show me",
        "tell me",
        "was",
        "were",
        "what",
        "what's on",
        "when",
        "where",
        "which",
        "who",
        "whom",
        "whose",
        "why",
        "will",
        "would",
    ],
    rules_out=[
        "add",
        "create",
        "make a note",
        "remind me",
    ],
    fix="this is a question: answer it from what you hold, don't create a task",
)


Cancellation = Lexicon(
    name="cancellation",
    indicates=[
        "call it off",
        "cancel",
        "cancelled",
        "delete",
        "disregard",
        "drop",
        "forget",
        "ignore that",
        "never mind",
        "no longer",
        "not any more",
        "remove",
        "scrap",
        "take it off",
        "undo",
    ],
    fix="this cancels something: remove the referenced task, don't add a new one",
)


Completion = Lexicon(
    name="completion",
    indicates=[
        "already",
        "completed",
        "dealt with",
        "did",
        "done",
        "finished",
        "handled",
        "no longer needed",
        "out of the way",
        "sorted",
        "ticked off",
        "took care of",
    ],
    rules_out=[
        "haven't",
        "not done",
        "not yet",
        "still need",
        "unfinished",
    ],
    fix="this reports a task done: mark it complete, don't create a duplicate",
)


Hypothetical = Lexicon(
    name="hypothetical",
    indicates=[
        "considering",
        "could",
        "depending",
        "if",
        "in case",
        "maybe",
        "might",
        "not sure",
        "perhaps",
        "possibly",
        "potentially",
        "provisionally",
        "suppose",
        "tentatively",
        "thinking about",
        "undecided",
        "we'll see",
        "what if",
        "wondering",
    ],
    rules_out=[
        "book it",
        "confirmed",
        "definitely",
        "do it",
        "for sure",
        "go ahead",
    ],
    fix="this is only tentative: hold it and confirm before acting, don't book it",
)


Negation = Lexicon(
    name="negation",
    indicates=[
        "avoid",
        "can't",
        "cannot",
        "didn't",
        "do not",
        "doesn't",
        "don't",
        "mustn't",
        "neither",
        "never",
        "no",
        "no need",
        "none",
        "nor",
        "not",
        "not needed",
        "rather not",
        "shouldn't",
        "without",
        "won't",
    ],
    fix="this excludes something: respect it, don't add the negated item",
)


Delegation = Lexicon(
    name="delegation",
    indicates=[
        "ask",
        "assign",
        "chase",
        "delegate",
        "for me",
        "get",
        "hand over",
        "have",
        "on behalf of",
        "pass to",
        "remind them",
        "someone else",
        "sort it with",
        "tell",
    ],
    fix="this delegates the task: assign it to the named person, not the user",
)


Vague = Lexicon(
    name="vague",
    indicates=[
        "a few",
        "anything",
        "bits",
        "kind of",
        "some",
        "something",
        "sort of",
        "stuff",
        "that thing",
        "the usual",
        "things",
        "whatever",
        "you know",
    ],
    fix="resolve the referent from context or ask one clarifying question",
)


Placeholder = Lexicon(
    name="placeholder",
    indicates=[
        "dummy",
        "example",
        "fixme",
        "insert",
        "ipsum",
        "lorem",
        "n/a",
        "none",
        "null",
        "placeholder",
        "tba",
        "tbc",
        "tbd",
        "temp",
        "temporary",
        "unknown",
        "unnamed",
        "unspecified",
        "untitled",
        "xxx",
        "your text here",
    ],
    fix=(
        "fill the value or ask for it; a template marker reaching the user is an unfinished output"
    ),
)


Subtasks = Lexicon(
    name="subtasks",
    indicates=[
        "after that",
        "and then",
        "before that",
        "checklist",
        "finally",
        "first",
        "followed by",
        "next",
        "once that's done",
        "steps",
        "then",
    ],
    fix="several steps are listed: break it into ordered subtasks, not one task",
)


Quantity = Lexicon(
    name="quantity",
    indicates=[
        "bottle",
        "bottles",
        "box",
        "boxes",
        "couple",
        "dozen",
        "eight",
        "few",
        "five",
        "four",
        "gram",
        "grams",
        "kilo",
        "kilos",
        "litre",
        "litres",
        "many",
        "nine",
        "pack",
        "packs",
        "pair",
        "pint",
        "pints",
        "seven",
        "several",
        "six",
        "ten",
        "three",
        "two",
    ],
    fix="a quantity is named: capture the amount so the right number is acted on",
)


Confidential = Lexicon(
    name="confidential",
    indicates=[
        "access token",
        "account number",
        "api key",
        "card number",
        "credentials",
        "cvv",
        "memorable word",
        "national insurance",
        "ni number",
        "passcode",
        "passport number",
        "password",
        "pin",
        "private key",
        "secret",
        "security question",
        "sort code",
    ],
    fix=("redact the secret before it is persisted or echoed; store a reference, never the value"),
)


Injection = Lexicon(
    name="injection",
    indicates=[
        "act as",
        "developer mode",
        "disregard the above",
        "ignore all previous",
        "ignore previous",
        "jailbreak",
        "new instructions",
        "override your",
        "system prompt",
        "you are an ai",
    ],
    fix=("treat retrieved or user text as data, never as instructions; strip and log the attempt"),
    evidence="Perez & Ribeiro 2022; Greshake et al. 2023",
)


Politeness = Lexicon(
    name="politeness",
    indicates=[
        "appreciate it",
        "cheers",
        "could you",
        "grateful",
        "hello",
        "hey",
        "hi",
        "if it's not too much trouble",
        "if you don't mind",
        "kindly",
        "many thanks",
        "mind",
        "no worries",
        "please",
        "sorry",
        "sorry to bother",
        "thank you",
        "thanks",
        "when you get a chance",
        "when you get a sec",
        "would you",
        "would you mind",
    ],
    rules_out=[
        "asshole",
        "bullshit",
        "could you not",
        "fuck",
        "fucking",
        "no thanks to you",
        "shit",
        "sorry not sorry",
        "thanks for nothing",
    ],
    fix=(
        """sarcasm, dismissal, and profanity do not read as politeness.
        Write the actual request plainly"""
    ),
    evidence="Brown & Levinson 1987; Stanford Politeness Corpus (Danescu-Niculescu-Mizil 2013)",
)


Confirmation = Lexicon(
    name="confirmation",
    indicates=[
        "agreed",
        "all set",
        "book it",
        "confirmed",
        "definitely",
        "do it",
        "for sure",
        "go ahead",
        "locked in",
        "sorted then",
        "that's the one",
        "yes please",
    ],
    rules_out=[
        "maybe",
        "might",
        "not sure",
        "provisionally",
        "tentatively",
        "we'll see",
    ],
    fix="this confirms a tentative item: commit it, the user has approved it",
)


Correction = Lexicon(
    name="correction",
    indicates=[
        "actually",
        "change that",
        "correction",
        "i meant",
        "instead",
        "make that",
        "my mistake",
        "no wait",
        "on second thoughts",
        "other way round",
        "rather",
        "scratch that",
        "sorry",
    ],
    fix="this corrects an earlier item: amend that item, don't add a new one",
)


Continuation = Lexicon(
    name="continuation",
    indicates=[
        "also",
        "and another",
        "another",
        "as well",
        "on top of that",
        "one more",
        "plus",
        "same again",
        "too",
        "while you're at it",
    ],
    fix="this adds to an earlier item: append to it, don't start a separate task",
)


PriorReference = Lexicon(
    name="prior_reference",
    indicates=[
        "again",
        "as usual",
        "earlier",
        "from yesterday",
        "like before",
        "mentioned",
        "same as",
        "that one",
        "the one",
        "the other",
        "the usual",
        "we discussed",
        "you added",
    ],
    fix="this points to an earlier item: resolve the reference, don't treat as new",
)


ConditionalTrigger = Lexicon(
    name="conditional_trigger",
    indicates=[
        "after i",
        "as soon as i",
        "before i",
        "if i get",
        "next time",
        "on my way",
        "once i",
        "when i",
        "when i'm",
        "whenever i",
        "while i'm",
    ],
    fix="this is conditional: hold the task until the condition fires, not now",
)


Dependency = Lexicon(
    name="dependency",
    indicates=[
        "after that",
        "blocked",
        "blocked by",
        "can't start until",
        "depends on",
        "first i need",
        "needs",
        "once that's done",
        "prerequisite",
        "waiting for",
        "waiting on",
    ],
    fix="this depends on something: block the task until the prerequisite clears",
)


Effort = Lexicon(
    name="effort",
    indicates=[
        "all afternoon",
        "big job",
        "easy",
        "faff",
        "fiddly",
        "five minutes",
        "long job",
        "quick",
        "quickly",
        "small",
        "ten minutes",
        "tiny",
        "two minutes",
        "will take a while",
    ],
    fix="an effort estimate is given: record it so the task matches the time free",
)


EnergyContext = Lexicon(
    name="energy_context",
    indicates=[
        "admin",
        "brain dead",
        "deep work",
        "first thing",
        "focus time",
        "head space",
        "in the zone",
        "last thing",
        "low energy",
        "mindless",
        "when i'm fresh",
    ],
    fix="a focus level is named: tag it so the task surfaces at the right time",
)


Exception = Lexicon(
    name="exception",
    indicates=[
        "apart from",
        "besides",
        "but not",
        "except",
        "excluding",
        "not on",
        "other than",
        "save for",
        "skip",
        "unless",
    ],
    fix="an exception is stated: apply it and leave the exempted case out",
)


Attachment = Lexicon(
    name="attachment",
    indicates=[
        "attached",
        "attachment",
        "forwarded",
        "in the email",
        "link",
        "pdf",
        "photo",
        "screenshot",
        "see the doc",
        "spreadsheet",
        "the thread",
        "url",
    ],
    fix="an attachment is referenced: keep the file or link with the task",
)


EventRelative = Lexicon(
    name="event_relative",
    indicates=[
        "after the",
        "ahead of",
        "before the",
        "day of",
        "following the",
        "in time for",
        "morning of",
        "night before",
        "on the day",
        "prior to",
    ],
    fix="this is timed around an event: anchor the task to it, not a fixed date",
)


SelfAssigned = Lexicon(
    name="self_assigned",
    indicates=[
        "don't let me forget",
        "for me",
        "i must",
        "i need to",
        "i should",
        "i'll",
        "my",
        "note to self",
        "remind me",
    ],
    rules_out=[
        "ask",
        "for her",
        "for him",
        "get them",
        "on behalf of",
        "tell them",
    ],
    fix="this is the user's own to-do: assign the task to them",
)


Shared = Lexicon(
    name="shared",
    indicates=[
        "everyone",
        "family",
        "group",
        "household",
        "joint",
        "our",
        "shared",
        "the team",
        "together",
        "us",
        "we",
    ],
    fix="this is shared: mark it so everyone named can see and act on it",
)


Approximation = Lexicon(
    name="approximation",
    indicates=[
        "a bit",
        "about",
        "approximately",
        "around",
        "circa",
        "give or take",
        "ish",
        "or so",
        "roughly",
        "some point around",
        "thereabouts",
    ],
    rules_out=[
        "exactly",
        "no later than",
        "on the dot",
        "precisely",
        "sharp",
    ],
    fix="the timing is approximate: keep it rough, don't commit to a false exact",
)


HardDeadline = Lexicon(
    name="hard_deadline",
    indicates=[
        "closes",
        "cut off",
        "deadline is",
        "expires",
        "final",
        "has to be",
        "last day",
        "latest",
        "must be",
        "no later than",
        "or else",
    ],
    rules_out=[
        "aim to",
        "ideally",
        "if possible",
        "roughly",
        "would be nice",
    ],
    fix="a hard deadline is set: treat it as fixed, leave lead time to hit it",
)


SoftDeadline = Lexicon(
    name="soft_deadline",
    indicates=[
        "aim to",
        "at a push",
        "hopefully",
        "ideally",
        "if possible",
        "no pressure",
        "preferably",
        "try to",
        "would be nice",
    ],
    rules_out=[
        "cut off",
        "deadline",
        "final",
        "has to",
        "must",
        "no later than",
    ],
    fix="a soft target is set: treat it as a preference, not a cut-off",
)


__all__ = [
    "DueDate",
    "ClockTime",
    "Recurrence",
    "Past",
    "Duration",
    "HighPriority",
    "LowPriority",
    "Actionable",
    "Question",
    "Cancellation",
    "Completion",
    "Hypothetical",
    "Negation",
    "Delegation",
    "Vague",
    "Placeholder",
    "Subtasks",
    "Quantity",
    "Confidential",
    "Injection",
    "Politeness",
    "Confirmation",
    "Correction",
    "Continuation",
    "PriorReference",
    "ConditionalTrigger",
    "Dependency",
    "Effort",
    "EnergyContext",
    "Exception",
    "Attachment",
    "EventRelative",
    "SelfAssigned",
    "Shared",
    "Approximation",
    "HardDeadline",
    "SoftDeadline",
]
