from __future__ import annotations

from lexguard.lexicon import Lexicon, Source

Rejection = Lexicon(
    name="rejection",
    indicates=[
        "made it worse",
        "no that's not",
        "nope",
        "not quite right",
        "not what i asked for",
        "revert that",
        "still broken",
        "still doesn't work",
        "still not working",
        "that broke",
        "that didn't work",
        "that doesn't work",
        "that's incorrect",
        "that's not correct",
        "that's not it",
        "that's not right",
        "that's not what i asked",
        "that's not what i said",
        "that's wrong",
        "this is wrong",
        "undo that",
        "wrong answer",
        "you broke",
        "you got it wrong",
        "you misunderstood",
    ],
    rules_out=[
        "no biggie",
        "no hurry",
        "no need",
        "no problem",
        "no rush",
        "no thanks",
        "no worries",
        "oh no",
    ],
    fix="treat the previous turn as rejected; find what was wrong and redo it, don't repeat it",
    evidence=(
        Source("Schegloff et al. 1977 (conversational repair)", "https://doi.org/10.2307/413107"),
        Source("Higashinaka et al. 2016 (DBDC)", "https://aclanthology.org/L16-1502/"),
    ),
)


Frustration = Lexicon(
    name="frustration",
    indicates=[
        "already said that",
        "already told you",
        "bloody hell",
        "bullshit",
        "come on",
        "dammit",
        "damn it",
        "for crying out loud",
        "for fuck's sake",
        "for god's sake",
        "for the last time",
        "for the third time",
        "fucking",
        "goddamn",
        "how many times",
        "i keep telling you",
        "jesus christ",
        "no no no",
        "not again",
        "over and over",
        "stop doing",
        "this is ridiculous",
        "useless",
        "what the hell",
        "why do you keep",
        "why won't you",
        "wtf",
        "yet again",
    ],
    rules_out=[
        "damn good",
        "fucking awesome",
        "fucking brilliant",
        "fucking great",
        "fucking love",
        "fucking perfect",
        "hell yeah",
        "hell yes",
    ],
    fix="acknowledge the repeated ask and change approach; do not make the user repeat it again",
    evidence=(
        Source(
            "Ang et al. 2002 (annoyance/frustration prosody)",
            "https://www.isca-archive.org/icslp_2002/ang02_icslp.html",
        ),
        Source(
            "Klein et al. 2002 (frustration in HCI)",
            "https://doi.org/10.1016/S0953-5438(01)00053-4",
        ),
    ),
)


UnverifiedClaim = Lexicon(
    name="unverified_claim",
    indicates=[
        "all good now",
        "bug is fixed",
        "bug is gone",
        "done and working",
        "everything works now",
        "fixed it",
        "good to go",
        "it works now",
        "no more errors",
        "now it works",
        "problem solved",
        "that did the trick",
        "that fixes it",
        "that's fixed",
        "the fix works",
        "this fixes it",
        "this resolves it",
        "this will work",
        "this works now",
        "works as expected",
        "works perfectly",
        "you're all set",
    ],
    rules_out=[
        "confirmed by",
        "hopefully",
        "i checked",
        "i confirmed",
        "i ran",
        "i tested",
        "i think",
        "in theory",
        "might",
        "not sure",
        "output shows",
        "probably",
        "ran the tests",
        "should",
        "tests pass",
        "tests passed",
        "the logs show",
        "verified",
    ],
    fix="run it and show the result before claiming it works, or say you have not verified it",
    evidence=(
        Source(
            "Huang et al. 2024 (intrinsic self-correction limits)",
            "https://arxiv.org/abs/2310.01798",
        ),
        Source("Hyland 2005 (boosters)"),
    ),
)


ScopeCreep = Lexicon(
    name="scope_creep",
    indicates=[
        "also added",
        "also cleaned up",
        "also fixed",
        "also improved",
        "also refactored",
        "also updated",
        "as a bonus",
        "beyond what you asked",
        "bonus feature",
        "even though you didn't ask",
        "for good measure",
        "i decided to also",
        "i took the liberty",
        "i took the opportunity",
        "i went ahead and",
        "on top of that i",
        "since i was already",
        "since i was in there",
        "took the liberty",
        "while i was at it",
        "while i was in there",
        "you didn't ask but",
    ],
    rules_out=[
        "as requested",
        "as you asked",
        "like you asked",
        "per your request",
        "which you requested",
        "you asked me to",
        "you wanted",
    ],
    fix="do only what was asked; raise extra work as a suggestion instead of doing it unprompted",
    evidence=(
        Source(
            "Krakovna et al. 2020 (specification gaming)",
            "https://deepmind.google/blog/specification-gaming-the-flip-side-of-ai-ingenuity/",
        ),
        Source("PMI (scope creep)"),
    ),
)


Stuck = Lexicon(
    name="stuck",
    indicates=[
        "back to square one",
        "can't figure out",
        "can't get it to",
        "can't seem to",
        "dead end",
        "going in circles",
        "hit a wall",
        "i give up",
        "i'm stuck",
        "keep getting the same",
        "keeps failing",
        "no luck",
        "no matter what i try",
        "not making progress",
        "nothing i try",
        "out of ideas",
        "out of options",
        "ran out of ideas",
        "same error again",
        "still can't",
        "still failing",
        "stuck on",
        "that didn't help",
        "tried everything",
    ],
    rules_out=[
        "figured it out",
        "finally got it",
        "got it working",
        "makes sense now",
        "solved it",
        "that worked",
        "up and running",
    ],
    fix=(
        "stop retrying the same thing; step back, state what you have ruled out, and change tack "
        "or ask"
    ),
    evidence=(
        Source(
            "Higashinaka et al. 2016 (Dialogue Breakdown Detection)",
            "https://aclanthology.org/L16-1502/",
        ),
        Source("Huang et al. 2024", "https://arxiv.org/abs/2310.01798"),
    ),
)


__all__ = [
    "Rejection",
    "Frustration",
    "UnverifiedClaim",
    "ScopeCreep",
    "Stuck",
]
