from __future__ import annotations

from lexguard.lexicon import Lexicon

FormatCode = Lexicon(
    name="format_code",
    indicates=[
        "class",
        "cli",
        "code",
        "config",
        "function",
        "implementation",
        "json",
        "module",
        "query",
        "regex",
        "repo",
        "script",
        "snippet",
        "sql",
        "yaml",
    ],
    rules_out=["conceptually", "don't write code", "explain only", "no code", "without code"],
    fix="answer with the actual code, not a description of it",
)
FormatList = Lexicon(
    name="format_list",
    indicates=[
        "as a list",
        "bullet",
        "bullet points",
        "bullets",
        "checklist",
        "dot points",
        "itemise",
        "itemize",
        "list",
        "listed",
        "numbered",
    ],
    rules_out=["essay", "full sentences", "no bullets", "no lists", "paragraphs", "prose"],
    fix="answer as a list, not reflowed prose",
)
FormatProse = Lexicon(
    name="format_prose",
    indicates=[
        "article",
        "essay",
        "flowing",
        "full sentences",
        "narrative",
        "no bullets",
        "no lists",
        "paragraphs",
        "prose",
        "write up",
    ],
    rules_out=["bullet", "bullets", "list", "numbered", "table"],
    fix="answer in prose, not bullets or a table",
)
FormatTable = Lexicon(
    name="format_table",
    indicates=[
        "columns",
        "comparison table",
        "grid",
        "matrix",
        "rows",
        "side by side",
        "spreadsheet",
        "table",
        "tabular",
    ],
    fix="lay the answer out as a table, not prose",
)
LengthLong = Lexicon(
    name="length_long",
    indicates=[
        "at length",
        "complete guide",
        "comprehensive",
        "deep dive",
        "detailed",
        "everything",
        "exhaustive",
        "expand on",
        "full breakdown",
        "in depth",
        "in detail",
        "thorough",
        "thoroughly",
    ],
    rules_out=["brief", "concise", "keep it short", "one line", "one sentence", "short", "tldr"],
    fix="go deep; a terse answer underserves this",
)
LengthShort = Lexicon(
    name="length_short",
    indicates=[
        "a few words",
        "brief",
        "briefly",
        "concise",
        "concisely",
        "in a nutshell",
        "keep it short",
        "no waffle",
        "one line",
        "one paragraph",
        "one sentence",
        "quick",
        "short",
        "shortly",
        "summarise",
        "summary",
        "terse",
        "tl;dr",
        "tldr",
    ],
    rules_out=[
        "at length",
        "comprehensive",
        "detailed",
        "exhaustive",
        "full",
        "in depth",
        "thorough",
    ],
    fix="keep it short: give the answer and stop",
)
NoCaveats = Lexicon(
    name="no_caveats",
    indicates=[
        "don't hedge",
        "don't lecture",
        "i know the risks",
        "i'm aware",
        "no caveats",
        "no disclaimers",
        "no hedging",
        "no need to warn",
        "no warnings",
        "skip the disclaimer",
        "spare me",
        "without the caveats",
    ],
    fix="drop the caveats; the risk is already accepted",
)
NoPreamble = Lexicon(
    name="no_preamble",
    indicates=[
        "answer only",
        "don't explain",
        "get to the point",
        "just give me",
        "just the",
        "no explanation",
        "no intro",
        "no introduction",
        "no preamble",
        "nothing else",
        "output only",
        "skip the",
        "straight to",
    ],
    fix="open on the answer, with no preamble",
)
StepByStep = Lexicon(
    name="step_by_step",
    indicates=[
        "first steps",
        "guide",
        "how do i",
        "how to",
        "in order",
        "instructions",
        "one at a time",
        "procedure",
        "step by step",
        "tutorial",
        "walk me through",
    ],
    fix="answer as ordered steps",
)
ToneCasual = Lexicon(
    name="tone_casual",
    indicates=[
        "casual",
        "chatty",
        "conversational",
        "friendly",
        "informal",
        "keep it human",
        "like a mate",
        "no jargon",
        "plain english",
        "relaxed",
    ],
    rules_out=["academic", "corporate", "formal", "official", "professional"],
    fix="answer in a casual register",
)
ToneFormal = Lexicon(
    name="tone_formal",
    indicates=[
        "academic",
        "business",
        "client facing",
        "corporate",
        "for publication",
        "formal",
        "official",
        "polished",
        "professional",
    ],
    rules_out=["banter", "casual", "chatty", "informal", "relaxed"],
    fix="answer in a formal register",
)

__all__ = [
    "FormatCode",
    "FormatList",
    "FormatProse",
    "FormatTable",
    "LengthLong",
    "LengthShort",
    "NoCaveats",
    "NoPreamble",
    "StepByStep",
    "ToneCasual",
    "ToneFormal",
]
