from __future__ import annotations

from lexguard.lexicon import Lexicon, Source

ContrastCliche = Lexicon(
    name="contrast_cliche",
    indicates=[
        "but rather",
        "enter the",
        "imagine if",
        "is not merely",
        "isn't merely",
        "it's less about",
        "it's not about",
        "more than just",
        "not just",
        "rather it's",
        "that's where",
        "the real question",
        "think of it as",
        "this is where",
    ],
    fix="make the positive claim directly rather than defining it against a strawman",
)
EmptyIntensifier = Lexicon(
    name="empty_intensifier",
    indicates=[
        "absolutely",
        "completely",
        "deeply",
        "enormously",
        "entirely",
        "exceptionally",
        "extremely",
        "genuinely",
        "highly",
        "hugely",
        "immensely",
        "incredibly",
        "massively",
        "profoundly",
        "quite",
        "quite literally",
        "really",
        "remarkably",
        "simply put",
        "terribly",
        "thoroughly",
        "totally",
        "tremendously",
        "truly",
        "utterly",
        "vastly",
        "very",
        "wholly",
    ],
    fix="delete the intensifier or replace it with the specific magnitude",
    evidence=(
        Source(cite="Quirk et al. 1985", url=""),
        Source(cite="Biber et al. 1999 (amplifiers)", url=""),
    ),
)
EngagementBait = Lexicon(
    name="engagement_bait",
    indicates=[
        "buckle up",
        "but wait",
        "here's the fun part",
        "here's the kicker",
        "let's dive in",
        "let's explore",
        "ready?",
        "spoiler",
        "the best part is",
        "the exciting part",
        "you might be wondering",
    ],
    fix="cut the tease and lead with the substance",
)
Padding = Lexicon(
    name="padding",
    indicates=[
        "as you know",
        "at its core",
        "basically",
        "clearly",
        "essentially",
        "fundamentally",
        "in essence",
        "in other words",
        "needless to say",
        "obviously",
        "of course",
        "put simply",
        "simply put",
        "that is to say",
    ],
    fix="delete the phrase; if the point needs restating the first statement was unclear",
)
Postamble = Lexicon(
    name="postamble",
    indicates=[
        "anything else",
        "don't hesitate",
        "feel free to",
        "happy to adjust",
        "hope that helps",
        "hope this helps",
        "i can also",
        "i hope this",
        "if you'd like",
        "in summary",
        "just say the word",
        "let me know if",
        "overall",
        "to summarise",
        "would you like me to",
    ],
    fix=(
        "end on the last substantive sentence; offers to help further belong in the interface, "
        "not the text"
    ),
)
Preamble = Lexicon(
    name="preamble",
    indicates=[
        "absolutely",
        "as you requested",
        "before we dive in",
        "certainly",
        "glad to",
        "happy to",
        "here is a",
        "here's a",
        "here's the",
        "i'd be happy",
        "i'll start by",
        "i've put together",
        "in this response",
        "let me",
        "of course",
        "sure",
        "to answer your question",
    ],
    fix="drop the opener and start with the answer; the first sentence should carry information",
)
Slop = Lexicon(
    name="slop",
    indicates=[
        "at the end of the day",
        "beacon",
        "bedrock",
        "best-in-class",
        "cornerstone",
        "crucial",
        "cutting-edge",
        "deep dive",
        "delve",
        "delving",
        "dive deep",
        "elevate",
        "embark",
        "ever-changing",
        "ever-evolving",
        "game changer",
        "game-changer",
        "harness",
        "holistic",
        "in today's fast-paced",
        "intricacies",
        "intricate",
        "journey",
        "landscape",
        "leverage",
        "leveraging",
        "meticulous",
        "meticulously",
        "multifaceted",
        "myriad",
        "navigate the complexities",
        "nuanced",
        "paradigm",
        "pivotal",
        "plethora",
        "profound",
        "realm",
        "robust",
        "seamless",
        "seamlessly",
        "showcase",
        "showcasing",
        "state-of-the-art",
        "synergy",
        "tapestry",
        "testament",
        "transformative",
        "underpin",
        "underpins",
        "underscore",
        "underscores",
        "unlock",
        "unlocking",
        "unparalleled",
        "unwavering",
        "world-class",
    ],
    fix="swap for a plain verb or noun, or add these to the sampler ban list",
    evidence=(
        Source(
            cite="Kobak et al. 2024 (excess vocabulary)", url="https://arxiv.org/abs/2406.07016"
        ),
        Source(cite="slop-forensics", url="https://github.com/sam-paech/slop-forensics"),
    ),
)
TransitionSlop = Lexicon(
    name="transition_slop",
    indicates=[
        "additionally",
        "as mentioned",
        "bear in mind",
        "consequently",
        "furthermore",
        "hence",
        "importantly",
        "in addition",
        "in conclusion",
        "it is important to note",
        "it is worth noting",
        "it's important to note",
        "it's worth noting",
        "keep in mind",
        "moreover",
        "notably",
        "remember that",
        "significantly",
        "that said",
        "therefore",
        "thus",
        "to conclude",
    ],
    fix="cut the connective; if the link between paragraphs needs stating, restructure instead",
)

__all__ = [
    "ContrastCliche",
    "EmptyIntensifier",
    "EngagementBait",
    "Padding",
    "Postamble",
    "Preamble",
    "Slop",
    "TransitionSlop",
]
