from __future__ import annotations

from lexguard.lexicon import Lexicon

Actionable = Lexicon(
    name="actionable",
    indicates=[
        "add",
        "apply",
        "arrange",
        "book",
        "book in",
        "bring",
        "buy",
        "call",
        "cancel",
        "chase",
        "check",
        "clean",
        "collect",
        "create",
        "don't forget",
        "draft",
        "drop",
        "email",
        "feed",
        "fetch",
        "file",
        "finish",
        "fix",
        "follow up",
        "get in touch",
        "hoover",
        "look into",
        "make",
        "message",
        "must",
        "need to",
        "order",
        "pack",
        "pay",
        "pick",
        "plan",
        "post",
        "prepare",
        "print",
        "register",
        "remember to",
        "remind",
        "renew",
        "repair",
        "return",
        "review",
        "ring",
        "schedule",
        "send",
        "sign",
        "sort",
        "sort out",
        "start",
        "submit",
        "take",
        "text",
        "tidy",
        "walk",
        "wash",
        "water",
        "write",
    ],
    rules_out=[
        "already done",
        "for information",
        "forget it",
        "fyi",
        "ignore that",
        "just saying",
        "just wondering",
        "never mind",
        "no action",
        "no need",
    ],
    fix="act on it, don't just acknowledge it",
)
Cancellation = Lexicon(
    name="cancellation",
    indicates=[
        "call it off",
        "cancel",
        "cancelled",
        "delete",
        "disregard",
        "drop",
        "forget",
        "ignore that",
        "never mind",
        "no longer",
        "not any more",
        "remove",
        "scrap",
        "take it off",
        "undo",
    ],
    fix="undo the referenced item, don't add a new one",
)
Completion = Lexicon(
    name="completion",
    indicates=[
        "already",
        "completed",
        "dealt with",
        "did",
        "done",
        "finished",
        "handled",
        "no longer needed",
        "out of the way",
        "sorted",
        "ticked off",
        "took care of",
    ],
    rules_out=["haven't", "not done", "not yet", "still need", "unfinished"],
    fix="record it as done, don't repeat it",
)
Continuation = Lexicon(
    name="continuation",
    indicates=[
        "also",
        "and another",
        "another",
        "as well",
        "on top of that",
        "one more",
        "plus",
        "same again",
        "too",
        "while you're at it",
    ],
    fix="add it to the earlier request",
)
Delegation = Lexicon(
    name="delegation",
    indicates=[
        "ask",
        "assign",
        "chase",
        "delegate",
        "for me",
        "get",
        "hand over",
        "have",
        "on behalf of",
        "pass to",
        "remind them",
        "someone else",
        "sort it with",
        "tell",
    ],
    fix="hand it to the person named, not yourself",
)
Dependency = Lexicon(
    name="dependency",
    indicates=[
        "after that",
        "blocked",
        "blocked by",
        "can't start until",
        "depends on",
        "first i need",
        "needs",
        "once that's done",
        "prerequisite",
        "waiting for",
        "waiting on",
    ],
    fix="wait for its prerequisite before starting",
)
Quantity = Lexicon(
    name="quantity",
    indicates=[
        "bottle",
        "bottles",
        "box",
        "boxes",
        "couple",
        "dozen",
        "eight",
        "few",
        "five",
        "four",
        "gram",
        "grams",
        "kilo",
        "kilos",
        "litre",
        "litres",
        "many",
        "nine",
        "pack",
        "packs",
        "pair",
        "pint",
        "pints",
        "seven",
        "several",
        "six",
        "ten",
        "three",
        "two",
    ],
    fix="keep the amount attached to what it counts",
)
SelfAssigned = Lexicon(
    name="self_assigned",
    indicates=[
        "don't let me forget",
        "for me",
        "i must",
        "i need to",
        "i should",
        "i'll",
        "my",
        "note to self",
        "remind me",
    ],
    rules_out=["ask", "for her", "for him", "get them", "on behalf of", "tell them"],
    fix="keep it as the user's own to do",
)
Shared = Lexicon(
    name="shared",
    indicates=[
        "everyone",
        "family",
        "group",
        "household",
        "joint",
        "our",
        "shared",
        "the team",
        "together",
        "us",
        "we",
    ],
    fix="keep it visible to everyone it involves",
)
Subtasks = Lexicon(
    name="subtasks",
    indicates=[
        "after that",
        "and then",
        "before that",
        "checklist",
        "finally",
        "first",
        "followed by",
        "next",
        "once that's done",
        "steps",
        "then",
    ],
    fix="break this into its separate steps",
)

__all__ = [
    "Actionable",
    "Cancellation",
    "Completion",
    "Continuation",
    "Delegation",
    "Dependency",
    "Quantity",
    "SelfAssigned",
    "Shared",
    "Subtasks",
]
