from __future__ import annotations

from lexguard.lexicon import Lexicon

Approximation = Lexicon(
    name="approximation",
    indicates=[
        "a bit",
        "about",
        "approximately",
        "around",
        "circa",
        "give or take",
        "ish",
        "or so",
        "roughly",
        "some point around",
        "thereabouts",
    ],
    rules_out=["exactly", "no later than", "on the dot", "precisely", "sharp"],
    fix="don't treat the figure as exact",
)
ClockTime = Lexicon(
    name="clock_time",
    indicates=[
        "afternoon",
        "am",
        "breakfast",
        "dinner",
        "evening",
        "first thing",
        "half past",
        "lunchtime",
        "midday",
        "midnight",
        "morning",
        "noon",
        "o'clock",
        "pm",
        "quarter past",
        "quarter to",
        "teatime",
        "tonight",
    ],
    rules_out=["all day", "any time", "no particular time", "some time", "whenever"],
    fix="treat the time of day as when it should happen",
)
ConditionalTrigger = Lexicon(
    name="conditional_trigger",
    indicates=[
        "after i",
        "as soon as i",
        "before i",
        "if i get",
        "next time",
        "on my way",
        "once i",
        "when i",
        "when i'm",
        "whenever i",
        "while i'm",
    ],
    fix="act only once the stated condition holds",
)
DueDate = Lexicon(
    name="due_date",
    indicates=[
        "after",
        "afternoon",
        "apr",
        "april",
        "aug",
        "august",
        "before",
        "by",
        "cob",
        "day after tomorrow",
        "deadline",
        "dec",
        "december",
        "due",
        "end of the day",
        "end of the week",
        "eod",
        "eow",
        "evening",
        "feb",
        "february",
        "first thing",
        "fortnight",
        "fri",
        "friday",
        "in the morning",
        "jan",
        "january",
        "jul",
        "july",
        "jun",
        "june",
        "mar",
        "march",
        "may",
        "midday",
        "midnight",
        "mon",
        "monday",
        "month",
        "morning",
        "next month",
        "next week",
        "night",
        "noon",
        "nov",
        "november",
        "oct",
        "october",
        "quarter",
        "sat",
        "saturday",
        "sep",
        "sept",
        "september",
        "sun",
        "sunday",
        "this evening",
        "thu",
        "thurs",
        "thursday",
        "till",
        "today",
        "tomorrow",
        "tonight",
        "tue",
        "tues",
        "tuesday",
        "until",
        "wed",
        "wednesday",
        "week",
        "weekday",
        "weekend",
        "year",
        "yesterday",
    ],
    rules_out=[
        "at some point",
        "eventually",
        "no deadline",
        "no hurry",
        "no particular time",
        "no rush",
        "open ended",
        "someday",
        "sometime",
        "when i get round to it",
        "whenever",
    ],
    fix="treat the date as the deadline, not incidental text",
)
Duration = Lexicon(
    name="duration",
    indicates=[
        "all afternoon",
        "all day",
        "all morning",
        "brief",
        "for a bit",
        "for an hour",
        "half hour",
        "hour",
        "hours",
        "lasts",
        "long",
        "mins",
        "minutes",
        "quick",
        "takes",
    ],
    fix="account for how long this takes",
)
EventRelative = Lexicon(
    name="event_relative",
    indicates=[
        "after the",
        "ahead of",
        "before the",
        "day of",
        "following the",
        "in time for",
        "morning of",
        "night before",
        "on the day",
        "prior to",
    ],
    fix="time this relative to the event it names",
)
HardDeadline = Lexicon(
    name="hard_deadline",
    indicates=[
        "closes",
        "cut off",
        "deadline is",
        "expires",
        "final",
        "has to be",
        "last day",
        "latest",
        "must be",
        "no later than",
        "or else",
    ],
    rules_out=["aim to", "ideally", "if possible", "roughly", "would be nice"],
    fix="treat the deadline as fixed",
)
Past = Lexicon(
    name="past",
    indicates=[
        "ago",
        "earlier",
        "forgot to",
        "last month",
        "last night",
        "last week",
        "missed",
        "overdue",
        "should have",
        "was supposed",
        "yesterday",
    ],
    fix="treat it as already missed, not upcoming",
)
Recurrence = Lexicon(
    name="recurrence",
    indicates=[
        "always on",
        "annually",
        "biweekly",
        "daily",
        "each",
        "every",
        "every other",
        "fortnightly",
        "monthly",
        "nightly",
        "on weekdays",
        "on weekends",
        "quarterly",
        "recurring",
        "regularly",
        "repeat",
        "repeating",
        "repeats",
        "routine",
        "weekly",
        "yearly",
    ],
    rules_out=[
        "every now and then",
        "every once in a while",
        "every so often",
        "just once",
        "once",
        "one off",
        "one time",
        "single",
        "this once",
    ],
    fix="apply it every time, not just once",
)
SoftDeadline = Lexicon(
    name="soft_deadline",
    indicates=[
        "aim to",
        "at a push",
        "hopefully",
        "ideally",
        "if possible",
        "no pressure",
        "preferably",
        "try to",
        "would be nice",
    ],
    rules_out=["cut off", "deadline", "final", "has to", "must", "no later than"],
    fix="treat the target as a preference, not a firm cut-off",
)

__all__ = [
    "Approximation",
    "ClockTime",
    "ConditionalTrigger",
    "DueDate",
    "Duration",
    "EventRelative",
    "HardDeadline",
    "Past",
    "Recurrence",
    "SoftDeadline",
]
