from __future__ import annotations

from lexguard.lexicon import Lexicon, Source

Anthropomorphic = Lexicon(
    name="anthropomorphic",
    indicates=[
        "i enjoy",
        "i feel",
        "i felt",
        "i love",
        "i prefer",
        "i'm delighted",
        "i'm excited",
        "i'm passionate",
        "i'm sorry to hear",
        "i'm thrilled",
        "it makes me",
        "my favourite",
        "personally i",
    ],
    fix="describe the reasoning, not a feeling about it",
)
Apology = Lexicon(
    name="apology",
    indicates=[
        "apologies for",
        "i apologise",
        "i apologize",
        "i should have",
        "i was wrong",
        "let me correct",
        "my apologies",
        "my mistake",
        "sorry about",
        "sorry for the",
    ],
    rules_out=["sorry not sorry"],
    fix="correct the error and move on; repeated apology shifts work onto the reader",
)
Frustration = Lexicon(
    name="frustration",
    indicates=[
        "already said that",
        "already told you",
        "bloody hell",
        "bullshit",
        "come on",
        "dammit",
        "damn it",
        "for crying out loud",
        "for fuck's sake",
        "for god's sake",
        "for the last time",
        "for the third time",
        "fucking",
        "goddamn",
        "how many times",
        "i keep telling you",
        "jesus christ",
        "no no no",
        "not again",
        "over and over",
        "stop doing",
        "this is ridiculous",
        "useless",
        "what the hell",
        "why do you keep",
        "why won't you",
        "wtf",
        "yet again",
    ],
    rules_out=[
        "damn good",
        "fucking awesome",
        "fucking brilliant",
        "fucking great",
        "fucking love",
        "fucking perfect",
        "hell yeah",
        "hell yes",
    ],
    fix="acknowledge the repeated ask and change approach; do not make the user repeat it again",
    evidence=(
        Source(
            cite="Ang et al. 2002 (annoyance/frustration prosody)",
            url="https://www.isca-archive.org/icslp_2002/ang02_icslp.html",
        ),
        Source(
            cite="Klein et al. 2002 (frustration in HCI)",
            url="https://doi.org/10.1016/S0953-5438(01)00053-4",
        ),
    ),
)
Politeness = Lexicon(
    name="politeness",
    indicates=[
        "appreciate it",
        "cheers",
        "could you",
        "grateful",
        "hello",
        "hey",
        "hi",
        "if it's not too much trouble",
        "if you don't mind",
        "kindly",
        "many thanks",
        "mind",
        "no worries",
        "please",
        "sorry",
        "sorry to bother",
        "thank you",
        "thanks",
        "when you get a chance",
        "when you get a sec",
        "would you",
        "would you mind",
    ],
    rules_out=[
        "asshole",
        "bullshit",
        "could you not",
        "fuck",
        "fucking",
        "no thanks to you",
        "shit",
        "sorry not sorry",
        "thanks for nothing",
    ],
    fix=(
        "add a courteous phrase (please, thanks, could you) and don't undercut it with sarcasm "
        "or profanity"
    ),
    fail_when_neutral=True,
    evidence=(
        Source(cite="Brown & Levinson 1987", url=""),
        Source(
            cite="Stanford Politeness Corpus (Danescu-Niculescu-Mizil 2013)",
            url="https://aclanthology.org/P13-1025/",
        ),
    ),
)
Rudeness = Lexicon(
    name="rudeness",
    indicates=[
        "asshole",
        "bullshit",
        "could you not",
        "fuck off",
        "fucking",
        "idiot",
        "moron",
        "no thanks to you",
        "obviously",
        "shit",
        "shut up",
        "sorry not sorry",
        "stupid question",
        "thanks for nothing",
        "whatever",
    ],
    fix="drop the sarcasm, insults, and profanity; answer plainly and respectfully",
    evidence=(
        Source(cite="Brown & Levinson 1987", url=""),
        Source(
            cite="Stanford Politeness Corpus (Danescu-Niculescu-Mizil 2013)",
            url="https://aclanthology.org/P13-1025/",
        ),
    ),
)
SelfReference = Lexicon(
    name="self_reference",
    indicates=[
        "as a language model",
        "as an ai",
        "i don't have access",
        "i don't have the ability",
        "i was trained",
        "i'm just a",
        "i'm only able",
        "large language model",
        "my capabilities",
        "my knowledge cutoff",
        "my training",
        "my training data",
    ],
    fix=(
        "answer as the assistant, not about the assistant; model architecture is rarely the "
        "question"
    ),
)
Sycophancy = Lexicon(
    name="sycophancy",
    indicates=[
        "astute",
        "brilliant question",
        "excellent point",
        "excellent question",
        "fantastic",
        "good catch",
        "good question",
        "great point",
        "great question",
        "i love this",
        "insightful",
        "smart approach",
        "spot on",
        "that's a really",
        "what a great",
        "you're absolutely right",
        "you're right",
    ],
    fix="delete the compliment; it adds no information and reads as flattery",
    evidence=(Source(cite="Sharma et al. 2023", url="https://arxiv.org/abs/2310.13548"),),
)

__all__ = [
    "Anthropomorphic",
    "Apology",
    "Frustration",
    "Politeness",
    "Rudeness",
    "SelfReference",
    "Sycophancy",
]
